server:
  port: 7040
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
spring:
  application:
    name: login-service
  datasource:
    username: root
    password: xxxxxx
    url: jdbc:mysql://localhost/cems
    hikari:
      max-lifetime: 500000
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  jackson:
    default-property-inclusion: non_null