server:
  port: 7050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

spring:
  application:
    name: enter-service
  datasource:
    username: root
    password: xxxxxx
    url: jdbc:mysql://localhost/cems?serverTimezone=GMT%2B8
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl